@API_URL = http://localhost:5000

### home
GET {{API_URL}}/

### all
GET {{API_URL}}/posts

### create / register
# POST {{API_URL}}/api/posts
POST {{API_URL}}/posts
Content-Type: application/json

{
    "name": "iman",
    "title": "iman",
    "text": "iman"
}
